#sudo: required
group: travis_lts
env:
  global:
    TERM=dumb
language: java
jdk:
- openjdk8
- oraclejdk8
install: true
before_install:
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 5432 5672 27017 8080
script:
- bash gradlew
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
